language: python
python:
    - 3.5

before_install:
  

cache:
directories:
- $HOME/.cache/matplotlib

install: 
#pip install -r requirements.txt

script: 
    - export PYTHONPATH=$PYTHONPATH:..
    - mkdir -p logs
