language: python
python:
    - 3.5

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y ipython3
  
install: pip install -r requirements.txt

script: 
    - export PYTHONPATH=$PYTHONPATH:..
    - mkdir -p logs
    - fc-cache 
    -  python tests/func/test_ozone.py
    - python tests/func/test_air_passengers.py
    - make PYTHON=python -f tests/Makefile build-test
