language: python
python:
    - 3.5

before_install:
  

cache:
directories:
- $HOME/.cache/matplotlib

install: 
    pip install scipy pandas sklearn matplotlib pydot dill pathos sqlalchemy

script: 
    - export PYTHONPATH=$PYTHONPATH:..
    - mkdir -p logs
    - rm -rf ~/.matplotlib
    - rm -rf ~/.cache/matplotlib
    - rm -rf ~/.matplotlib/fontList.cache  
    - fc-cache 
    - python ./tests/bugs/issue_36/display_version_info.py
    - python tests/func/test_ozone.py
    - python tests/func/test_air_passengers.py
    - make PYTHON=python -f tests/Makefile build-test
